/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface':                   '#f8f9ff',
        'surface-dim':               '#cbdbf5',
        'surface-bright':            '#f8f9ff',
        'surface-container-lowest':  '#ffffff',
        'surface-container-low':     '#eff4ff',
        'surface-container':         '#e5eeff',
        'surface-container-high':    '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'on-surface':                '#0b1c30',
        'on-surface-variant':        '#45464d',
        'inverse-surface':           '#213145',
        'inverse-on-surface':        '#eaf1ff',
        'outline':                   '#76777d',
        'outline-variant':           '#c6c6cd',
        'surface-tint':              '#565e74',
        'primary':                   '#0F172A',
        'on-primary':                '#ffffff',
        'primary-container':         '#131b2e',
        'on-primary-container':      '#7c839b',
        'inverse-primary':           '#bec6e0',
        'secondary':                 '#3B82F6',
        'on-secondary':              '#ffffff',
        'secondary-container':       '#2170e4',
        'on-secondary-container':    '#fefcff',
        'tertiary':                  '#10B981',
        'on-tertiary':               '#ffffff',
        'tertiary-container':        '#002113',
        'on-tertiary-container':     '#009668',
        'error':                     '#ba1a1a',
        'on-error':                  '#ffffff',
        'error-container':           '#ffdad6',
        'on-error-container':        '#93000a',
        'primary-fixed':             '#dae2fd',
        'primary-fixed-dim':         '#bec6e0',
        'on-primary-fixed':          '#131b2e',
        'background':                '#F8FAFC',
        'on-background':             '#0b1c30',
        'surface-variant':           '#d3e4fe',
        'surface-studio':            '#F8FAFC',
        'border-subtle':             '#E2E8F0',
        'maintenance-urgent':        '#EF4444',
        'tenant-active':             '#10B981',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm:      '0.125rem',
        md:      '0.375rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        full:    '9999px',
      },
      spacing: {
        'base':                     '4px',
        'stack-sm':                 '8px',
        'stack-md':                 '16px',
        'stack-lg':                 '32px',
        'gutter':                   '24px',
        'container-margin-desktop': '40px',
        'container-margin-mobile':  '16px',
      },
      fontFamily: {
        'display-lg':         ['Hanken Grotesk', 'sans-serif'],
        'headline-md':        ['Hanken Grotesk', 'sans-serif'],
        'headline-sm':        ['Hanken Grotesk', 'sans-serif'],
        'headline-md-mobile': ['Hanken Grotesk', 'sans-serif'],
        'body-lg':            ['Inter', 'sans-serif'],
        'body-md':            ['Inter', 'sans-serif'],
        'body-sm':            ['Inter', 'sans-serif'],
        'label-caps':         ['JetBrains Mono', 'monospace'],
        sans:                 ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg':    ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md':   ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm':   ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg':       ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md':       ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm':       ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps':    ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
      },
      boxShadow: {
        sm:      '0px 4px 20px rgba(15, 23, 42, 0.08)',
        DEFAULT: '0px 4px 20px rgba(15, 23, 42, 0.08)',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
